server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/iatech_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

iatechnology:
  app:
    jwtSecret: "======================IA_TECHNOLOGY_SECRET_KEY_FOR_JWT_GENERATION_AND_VALIDATION_WHICH_SHOULD_BE_VERY_LONG======================"
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 2592000000

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
